bitbake.conf: Set ZSTD_THREADS to half of cpu number
Issue: LINCD-7197
Issue: LINCD-7279

The original value is very easy to cause do_packge error when cpu number is
larger, for example, 128 cores and 512G mem:

error: create archive failed: cpio: write failed - Cannot allocate memory"

Set the ZSTD_THREADS to half of the CPU number can avoid the error in my
testing.

(LOCAL REV: NOT UPSTREAM) -- Send to oe-core on 20211109

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>