lttng-modules: Fix build failure for kernel v5.15.58
Issue: LIN1022-1148

Backport from upstream d8254360c7f2ff9b3f945e9668d89c0b56b9bd91
("fix: net: skb: introduce kfree_skb_reason() (v5.15.58..v5.16)")

tmp-glibc/work/qemuarm-wrs-linux-gnueabi/lttng-modules/2.13.3-r0/
lttng-modules-2.13.3/src/probes/../../include/lttng/
tracepoint-event-impl.h:133:6:
error: conflicting types for 'trace_kfree_skb'; have 'void(struct sk_buff *, void *)'
  133 | void trace_##_name(_proto);
      |

(LOCAL REV: NOT UPSTREAM) -- sent to oe-core on 20220801

Signed-off-by: He Zhe <zhe.he@windriver.com>