packagegroup-core-x11-xserver: add opengl to REQUIRED_DISTRO_FEATURES
Issue: LINUXEXEC-23251 LINUXEXEC-6644

Fixes:
  ERROR: Nothing RPROVIDES 'xf86-video-vesa' (but /build/layers/oe-core/meta/recipes-graphics/packagegroups/packagegroup-core-x11-xserver.bb RDEPENDS on or otherwise requires it)
  xf86-video-vesa was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
  NOTE: Runtime target 'xf86-video-vesa' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['xf86-video-vesa']
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'packagegroup-core-x11-xserver', 'xf86-video-vesa']

(LOCAL REV: NOT UPSTREAM) -- Sent to oe-core on 20221205

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>