apt: fix do_package_qa failure
Issue: LIN1022-1140

bitbake nativesdk-apt failed with error:
ERROR: nativesdk-apt-2.4.5-r0 do_package_qa: QA Issue: nativesdk-apt installs files in /usr/local/oe-sdk-hardcoded-buildpath/sysroots/x86_64-pokysdk-linux/var/volatile, but it is expected to be empty [empty-dirs]

an empty dir apt is installed under /var/log/, fix the failure
by removing the empty dir apt as what we have done for target.
apt will create it when it does not exist.

(LOCAL REV: NOT UPSTREAM) -- sent to oe-core on 20220729

Signed-off-by: Changqing Li <changqing.li@windriver.com>