bitbake.conf: use ${RECIPE_SYSROOT} for PSEUDO_IGNORE_PATHS
Issue: LINCD-4545

When multilib enabled, there comes below error for packages which
inherit useradd bbclass randomly when build eSDK.
 $ bitbake image-name -c populate_sdk_ext
 Exception: subprocess.CalledProcessError: Command '/prj/tmp-glibc/work/intel_x86_64-wrs-linux/wrlinux-image-std/1.0-r5/lib32-recipe-sysroot/usr/bin/postinst-useradd-lib32-avahi' returned non-zero exit status 1.
 [snip]
 abort()ing pseudo client by server request. See https://wiki.yoctoproject.org/wiki/Pseudo_Abort for more details on this.
 Check logfile: /prj/tmp-glibc/work/intel_x86_64-wrs-linux/wrlinux-image-std/1.0-r5/pseudo//pseudo.log
 ERROR: lib32-avahi: useradd command did not succeed.
 ERROR: Logfile of failure stored in: /prj/tmp-glibc/work/intel_x86_64-wrs-linux/wrlinux-image-std/1.0-r5/temp/log.do_sdk_depends.20567

 $ cat  /prj/tmp-glibc/work/intel_x86_64-wrs-linux/wrlinux-image-std/1.0-r5/pseudo//pseudo.log
 [snip]
 path mismatch [1 link]: ino 26553244 db '/prj/tmp-glibc/work/intel_x86_64-wrs-linux/wrlinux-image-std/1.0-r5/recipe-sysroot/etc/group'
req '/prj/tmp-glibc/work/intel_x86_64-wrs-linux/wrlinux-image-std/1.0-r5/recipe-sysroot/etc/group.33605'.
 [snip]

 Check the PSEUDO_IGNORE_PATHS in [1], the recipe-sysroot part is
 /prj/tmp-glibc/work/corei7-32-wrsmllib32-linux/lib32-avahi/0.8-r0/recipe-sysroot.

 Use ${RECIPE_SYSROOT} for PSEUDO_IGNORE_PATHS to guarantee the
 recipe-syroot part to be /prj/tmp-glibc/work/intel_x86_64-wrs-linux/wrlinux-image-std/1.0-r5/recipe-sysroot
 to fix the above issue.

 Meanwhile the original expression also matches recipe-sysroot-native,
 so also explicitly set ${RECIPE_SYSROOT_NATIVE} to fix the gap.

 [1] /prj/tmp-glibc/work/intel_x86_64-wrs-linux/wrlinux-image-std/1.0-r5/lib32-recipe-sysroot/usr/bin/postinst-useradd-lib32-avahi

(LOCAL REV: NOT UPSTREAM) - Rejected by upstream and the issue still
                            exists and just rebase to avoid regression failure

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>